import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/commons/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

const cabinetGrotesk = localFont({
  variable: "--font-cabinet",
  src: [
    {
      path: "../../public/fonts/CabinetGrotesk-Regular.otf",
      weight: "400",
    },
    {
      path: "../../public/fonts/CabinetGrotesk-Light.otf",
      weight: "200",
    },
    {
      path: "../../public/fonts/CabinetGrotesk-Bold.otf",
      weight: "600",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cabinetGrotesk.className} flex w-full bg-white min-h-screen`}>
        <div className="flex flex-col items-center w-[20%] min-h-screen sticky mt-[30vh]">
          <Navbar />
        </div>
        <div className="w-[80%] min-h-screen overflow-scroll">{children}</div>
      </body>
    </html>
  );
}
